apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  COMPOSE_PROJECT_NAME: "todo-app"
  COMPOSE_FILE: "docker-compose.yaml"
  REACT_APP_API_ENDPOINT: "http://localhost:8080"
  DB_HOST: "mongodb"
  DB_NAME: "test"
  DB_USER: "appuser"
  DB_IMAGE_TAG: "4.4.1"
  DB_STORAGE_SIZE: "1Gi"
  DB_REPLICA_COUNT: "1"
  FRONTEND_REPLICA_COUNT: "2"
  FRONTEND_INGRESS_HOST: "todo.docker.internal"
  API_REPLICA_COUNT: "2"
  API_INGRESS_HOST: "todo-api.docker.internal"
