apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  #FRONTEND_REPLICA_COUNT in .env
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ehtishamasghar13/go-to-do-frontend:rc
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: todo-app-config

