apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  MONGODB_ROOT_PASSWORD: adminpass
  MONGODB_USERNAME: appuser
  MONGODB_PASSWORD: apppass

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  DB_PASSWORD: apppass

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
stringData:
  REACT_APP_API_ENDPOINT: http://localhost:8080
