name: CI build app to docker images and push to dockerhub

on:
  push:
    branches:
      - main


jobs:
  frontend:
    name: Frontend Build and Push
    runs-on: ubuntu-latest
    if: >
      contains(toJson(github.event.commits.*.added), 'client/') ||
      contains(toJson(github.event.commits.*.modified), 'client/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ehtishamasghar13/frontend:latest client/
          docker push ehtishamasghar13/frontend:latest

  backend:
    name: Backend Build and Push
    runs-on: ubuntu-latest
    if: "contains(toJson(github.event.commits.*.added), 'server/**') || contains(toJson(github.event.commits.*.modified), 'server/**')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Build Backend
        run: |
          cd server
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ehtishamasghar13/backend:latest server/
          docker push ehtishamasghar13/backend:latest
