name: CI build app to docker images and push to dockerhub

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Frontend Build and Push
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        if: "contains(toJson(github.event.commits.*.added), 'client/') || contains(toJson(github.event.commits.*.modified), 'client/')"
        run: |
          docker build -t ehtishamasghar13/frontend:latest client/
          docker push ehtishamasghar13/frontend:latest


