name: CI build app to docker images and push to dockerhub

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "server/**"

jobs:
  build:
    name: Frontend Build and Push
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image if changes in client directory
        if: ${{ contains(github.event_paths, 'client/') }}        
        run: |
          docker build -t ehtishamasghar13/frontend:latest client/
          docker push ehtishamasghar13/frontend:latest

      - name: Build and Push Docker Image if changes in server directory
        if: ${{ contains(github.event_paths, 'server/') }}
        run: |
          docker build -t ehtishamasghar13/backend:latest server/
          docker push ehtishamasghar13/backend:latest