name: CI build app to docker images and push to dockerhub

on:
  push:
    paths:
      - 'client/**' # Trigger only if changes are made in the client directory
      - 'server/**' # Trigger only if changes are made in the server directory

jobs:
  run_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run if changes in client directory
        if: ${{ contains(github.event_paths, 'client/') }}
        run: |
          docker build -t ehtishamasghar13/frontend:latest client/
          docker push ehtishamasghar13/frontend:latest

      - name: Run if changes in server directory
        if: ${{ contains(github.event_paths, 'server/') }}
        run: |
          docker build -t ehtishamasghar13/backend:latest server/
          docker push ehtishamasghar13/backend:latest


