name: CI server build app to docker images and push to dockerhub

on:
  push:
    paths:
      - 'server/**' # Trigger only if changes are made in the server directory

jobs:
  run_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run if changes in client directory
        run: |
          docker build -t ehtishamasghar13/server:latest client/
          docker push ehtishamasghar13/server:latest
